### ISSUE TITLE
tick() causes error

### ISSUE THREAD

**Issue by nin-jin** [maverick-js/signals#12]
```ts
import { signal, effect, tick } from '@maverick-js/signals'

let res = []
const A = signal(0)
const H = effect( ()=> res.push( A() ) )

A.set(1); tick()

$mol_assert_like( res, [ 1 ] )
```

[Sandbox](https://eval.js.hyoo.ru/#!code=const%20%7B%20signal%2C%20effect%2C%20tick%20%7D%20%3D%20%24mol_import.module%28%0A%09'https%3A%2F%2Fesm.sh%2F%40maverick-js%2Fsignals'%0A%29%0A%0Alet%20res%20%3D%20%5B%5D%0Aconst%20A%20%3D%20signal%280%29%0Aconst%20H%20%3D%20effect%28%20%28%29%3D%3E%20res.push%28%20A%28%29%20%29%20%29%0A%0AA.set%281%29%3B%20tick%28%29%0A%0A%24mol_assert_like%28%20res%2C%20%5B%201%20%5D%20%29/run=true)

**Comment by mihar-22** [comment]
Effects can return a dispose function and we don't currently type check it. I'll probably add it next patch.

It should work if you void the effect return:

```js
const H = effect(() => void res.push(A()));
```

**Comment by mihar-22** [comment]
We type check the returned value from the effect now so this issue has been resolved :)
