### ISSUE TITLE
Create computeds inside other computeds

### ISSUE THREAD

**Issue by GDX64** [maverick-js/signals#15]
Can I create computeds inside other computeds? Are they going to be garbage collected?

**Comment by mihar-22** [comment]
You can but you need to make sure it's `scoped` so that when the root computed re-runs it disposes of old computeds:

```ts
root((dispose) => {
  const foo = computed(() => {
    const bar = computed(() => /* ... */);
    // ...
  }, { scoped: true });

  // ...

  dispose();
);
```

**Comment by GDX64** [comment]
So let's supose that in your example the foo computed runs once and returns a bar1, then it runs a seccond time and returns a bar2, the bar1 reactivity is still going to work?

**Comment by mihar-22** [comment]
This example isn't the best, if you can share what you're trying to do then I can help better.

**Comment by GDX64** [comment]
I want to build some dynamic computation trees like this one:

```typescript
import { signal, computed, root } from '@maverick-js/signals';

describe('tree sum', () => {
  test('simple sum', () => {
    root((dispose) => {
      const arr = [...Array(16)].map((_, v) => signal(v));
      const tree = fromArr(arr);
      expect(tree()).toBe(120);
      arr[0].set(10);
      expect(tree()).toBe(130);
      dispose();
    });
  });
});

type Fn = () => number;
function sumTreeFn(left?: Fn, right?: Fn) {
  return computed(() => {
    return (left?.() ?? 0) + (right?.() ?? 0);
  });
}

function fromArr(arr: Fn[]): Fn {
  if (arr.length <= 2) {
    return sumTreeFn(arr[0], arr[1]);
  }
  return sumTreeFn(
    fromArr(arr.slice(0, Math.floor(arr.length / 2))),
    fromArr(arr.slice(Math.floor(arr.length / 2)))
  );
}
```

**Comment by mihar-22** [comment]
Sorry for the late response @GDX64! The example you showcased will work as expected. There's a change in the latest release to scope all computed's by default to avoid mem leaks. After upgrading feel free to remove the `{ scoped: true }` option.
