### ISSUE TITLE
Docs for computed options

### ISSUE THREAD

**Issue by yurivish** [maverick-js/signals#16]
In playing with Maverick Signals I came across a few neat features related to `computed` signals that I didn't see covered by the current README. It would be great if these had a little more documentation, since they seem quite useful. 

- The `dirty` option to `computed`
- The `scoped` option to `computed`
-  The [`initial`](https://github.com/maverick-js/signals/blob/ee7c4b1e277a9e6cc942a7bcf5541309d99f0bf7/src/signals.ts#L61) argument to `computed` and when it applies. I played with it briefly and seems that if you construct a computed with `computed(f, { initial })` then the value of `f()` is returned when peeking or reading the signal, and I wasn't sure when the initial value is used.

---

I was also wondering about the nested computed behavior mentioned in [this issue](https://github.com/maverick-js/signals/issues/15), which might deserve a little "note" section in the docs.
  
In particular, I was wondering if this is something to watch out for when building a DOM library on top of Signals where each component is a function and you can't be sure whether a `computed` contains a nested call to `computed`. 
   
For example, if a component has a computed array of children, and those children are also components that have `computed` values inside them, when will the nested `computed`s be disposed? Or more generally –  if we want to ensure that child `computed` signals are disposed of at the appropriate time, should we always create computeds with `{ scoped: true }` just in case the computed function might transitively contain calls to `computed`, and would not doing so potentially result in a memory leak?

**Comment by mihar-22** [comment]
Ye I agree we should definitely document those options!

> The [initial](https://github.com/maverick-js/signals/blob/ee7c4b1e277a9e6cc942a7bcf5541309d99f0bf7/src/signals.ts#L61) argument to computed and when it applies. I played with it briefly and seems that if you construct a computed with computed(f, { initial }) then the value of f() is returned when peeking or reading the signal, and I wasn't sure when the initial value is used.

This is a legacy option that was required when computed was run completely async. This is redundant now since it's sync so we can safely remove it.

> In particular, I was wondering if this is something to watch out for when building a DOM library on top of Signals where each component is a function and you can't be sure whether a computed contains a nested call to computed.

> For example, if a component has a computed array of children, and those children are also components that have computed values inside them, when will the nested computeds be disposed? Or more generally – if we want to ensure that child computed signals are disposed of at the appropriate time, should we always create computeds with { scoped: true } just in case the computed function might transitively contain calls to computed, and would not doing so potentially result in a memory leak?

You raise a good point here. It comes from a decision in the old signals model that I'd say isn't right here. I agree we should scope computed's out of the box to avoid possible memory leaks. I'll make the change.

**Comment by yurivish** [comment]
Hey, I got a notification this was closed but had a look and didn’t see the options documented in the [computed section](https://github.com/maverick-js/signals#computed). Out of curiosity, do you consider them part of the public API?
