### ISSUE TITLE
How to untrack a signal change

### ISSUE THREAD

**Issue by DominicTobias** [maverick-js/signals#22]
Hi, is there a way to set a signal without triggering observables? At first I thought I could use `untrack` but seems this is just for in an `effect`?

```ts
import { root, signal, untrack, effect, tick } from "@maverick-js/signals";

root((dispose) => {
  const $value = signal(0);

  effect(() => {
    console.log("$value changed to", $value());
  });

  // Still triggers the effect
  untrack(() => {
    $value.set(10);
  });

  tick()

  dispose()
});
```

**Comment by mihar-22** [comment]
Oh that's interesting, I haven't seen that come up before with untracking setting a value. Do you have an example to help me understand why this feature would be needed?

**Comment by DominicTobias** [comment]
It wasn't needed I was just thinking that I could do something like this:

```ts
effect(() => {
   scrollEl.scrollTo($scrollX(), $scrollY())
})
```

There was a situation where I wanted to set $scrollX/Y values without actually scrolling in the DOM (because the use scrolled it), and one situation where I was programmatically setting the values and wanted it to scroll.

Easily solved by doing the DOM `scrollTo` manually where I needed it anyway.
