### ISSUE TITLE
How to create an observable object/store

### ISSUE THREAD

**Issue by DominicTobias** [maverick-js/signals#24]
SolidJS has stores for deeper objects: https://www.solidjs.com/docs/latest/api#using-stores

I only need 1 level like: https://github.com/nanostores/nanostores#maps

The use case is a model which has an object of data (e.g. User) and I want to observe each prop inside it, and also compute derived values if some of those props change.

I think `signal` does a shallow check for changes and so what would you recommend to achieve 1 level deep observability?

```js
const user = {
  name: 'John',
  age: 17,
}

$user = signal(user)

const $doubleAge = computed(() => $user().age * 2);
```

`$doubleAge` should only re-compute if `age` changes

**Comment by DominicTobias** [comment]
I think it's acceptable for me just to explicitly write out a single for each field in the model. I guess this would be more of an issue for a large model (my largest is 86 props) or a deeply nested one.

**Comment by mihar-22** [comment]
It's pretty much the same thing except they might use proxies to support deep reactivity which would negatively impact mem/perf. Signals are cheaps, it's completely fine to create heaps of them.

Here's an example of how you can create a shallow reactive store (you can adapt the API how you like). This might be a little more efficient if you have a lot of computed properties via getters:

```ts
export class Store<Record> {
  readonly id = Symbol(__DEV__ ? 'STATE' : 0);
  readonly record: Record;

  private _descriptors: {
    [P in keyof Record]: TypedPropertyDescriptor<Record[P]>;
  };

  constructor(record: Record) {
    this.record = record;
    this._descriptors = Object.getOwnPropertyDescriptors(record);
  }

  create(): Record {
    const store = {} as Store<Record>,
      state = new Proxy(store, { get: (_, prop: any) => store[prop]() });

    for (const name of Object.keys(this.record) as any[]) {
      const getter = this._descriptors[name].get;
      store[name] = getter ? computed(getter.bind(state)) : signal(this.record[name]);
    }

    return store;
  }
}
```

Usage:

```ts
const factory = new Store({
  foo: 0,
  bar: '...',
  get baz() {
    return this.foo + 1;
  }
});

const store = factory.create();
```

**Comment by DominicTobias** [comment]
Very nice! thanks

**Comment by DominicTobias** [comment]
Finally got around to trying this out, the computed state is not updated any ideas why?

https://stackblitz.com/edit/typescript-htvjx5?file=index.ts

**Comment by mihar-22** [comment]
Two small mistakes:

1. Line 18 doesn't return a function: `store[prop]()` -> `store[prop]`
2. Line 57 use `this` to reference current store and not the initial record reference itself.

**Comment by DominicTobias** [comment]
Thanks that works 👌
