### ISSUE TITLE
Use object.is for equality check

### ISSUE THREAD

**Issue by snnsnn** [maverick-js/signals#30]
Not a major issue but i think `Object.is` would be better for cheking signal updates:

https://github.com/maverick-js/signals/blob/65f7fe9816595d3212130c3cc7d60986e6b8d346/src/core.ts#L398

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness

**Comment by mihar-22** [comment]
It would be but I'm not aware of the performance difference. If there's any benchmarks that we can look at that would help.

**Comment by snnsnn** [comment]
It is not about performance but reliability. Object.is returns true for `Object.is(NaN, NaN)` and false for `Object.is(0, -0)`. 

Since there is no implicit type conversion, it should be faster than `===`.

**Comment by mihar-22** [comment]
Performance is extremely important for our signals implementation, especially as the reacitvity graph becomes more deep. We have thousands of computations in our libraries that use this. Most rely on signals purely for performance. The trade off for checking something super rare like `NaN, NaN` and `-0, +0` needs to be justified.

**Comment by snnsnn** [comment]
I could not find any definitive benchmark results that runs extensive checks. I did run some using mitata, performance difference is marginal, which favors either of them depending on the compared values and the runtime.
