### ISSUE TITLE
Error Handling: Why not try parent's handlers before throwing

### ISSUE THREAD

**Issue by snnsnn** [maverick-js/signals#31]
Earlier I had an idea of using ownership tree for error handling too, was not sure if you would like it, but decided to show it anyway. I am using it in my reactive implementation, it works OK.

Basically we climb the ownership tree and see if parent scope has a handler. If you are  observing strict ownership as Solid does, assigning owners to effects, memos and components, it should have the same effect as re-throwing and catching it somewhere higher on the component tree.

Here is how I implemented it for my own reactive system:

```typescript
function handleError(scope: Computation, error: unknown) {
  const handlers = scope.handlers;
  let handled = false;
  for (let i = 0, len = handlers.length; i < len; i++) {
    try {
      handlers[i](error);
      handled = true;
      break; // Error is handled.
    } catch (rethrown: any) {
      error = rethrown;
    }
  }
  if (!handled) {
    if (scope.owner) {
      handleError(scope.owner, error);
    } else {
      throw error;
    }
  }
}
```

Now, parent scope will capture any error that may be thrown anywhere  down under, including effects and memos. The logic is same as context lookup.

This may provide a simpler mental model for tracking the error path in the application.

Here is how error boundary would look:

```typescript

export const ErrorBoundary: Component<{
  children: JSX.Element,
  fallback: JSX.Element | ((props: { error: any, reset: () => void }) => JSX.Element),
}> = ({ children, fallback }) => {
  const noError = Symbol('no-error');
  const error = signal<any>(noError);
  onError((err) => error.set(err));
  const reset = () => error.set(noError);
  return memo(() => (error() !== noError) ?
    typeof fallback === 'function' ?  fallback({ error: error(), reset }) : fallback :
    children
  );
};

```

**Comment by mihar-22** [comment]
This is already the case. Error handlers are copied on scope creation from parent to child.
