### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by snnsnn** [maverick-js/signals#32]
I believe using an array for `_sources`, `_observers`, `_children`, and `_handlers`, and an object for `_context`  will reduce bundle size significantly, provides cleaner types and remove null checking conditionals that lie on the hot execution path since those values end up being an array, or object if it is context, almost always.

Now a simple push and pop will suffice for many of the actions. Setting a context value will be reduced to a simple assignment, no need to create new object when inserting a new value, and we can take advantage of recursion for scope related actions like disposal.

**Comment by mihar-22** [comment]
I don’t follow. We’re already using arrays for the mentioned fields. Not sure how this relates to bundle size either.

**Comment by snnsnn** [comment]
Let me make it more concrete using `children` as an example.

In current implementation you are using `null` as the default value for the `_children` field, then assign the first child as the value and  then move to array when there are more than one child.

Here is how append is implemented:

```typescript
ScopeProto.append = function (this: Scope, child: Scope) {
  child[SCOPE] = this;

  if (!this._children) {
    this._children = child;
  } else if (Array.isArray(this._children)) {
    this._children.push(child);
  } else {
    this._children = [this._children, child];
  }

  child._context =
    child._context === defaultContext ? this._context : { ...this._context, ...child._context };

  if (this._handlers) {
    child._handlers = !child._handlers ? this._handlers : [...child._handlers, ...this._handlers];
  }
};
```

If we use an array for the _children value, we can remove half of the code:

```typescript
ScopeProto.append = function (this: Scope, child: Scope) {
  child[SCOPE] = this;
  this._children.push(child);
  child._context = {};
  this._handlers = [];
};
```

Now dispose simply becomes poping `_children` and disposing them. No need to check if it is an array, or a single scope or a child. 

And, about taking advantage of recursion, when a parent is disposed, we traverse children recursively and collect disposals.

**Comment by mihar-22** [comment]
We have to balance memory usage. I test all of this in our video player library and in the JS framework benchmark. You will get very slightly smaller bundle size and better perf with your suggestion at the cost of increased memory usage at scale.
